steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gateway-nginx:init', './nginx']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend-django:init', './django']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend-tomcat:init', './tomcat']
images: ['gcr.io/$PROJECT_ID/gateway-nginx:init', 'gcr.io/$PROJECT_ID/backend-django:init', 'gcr.io/$PROJECT_ID/frontend-tomcat:init']
