version: '3.7'

x-common-variables: &system-network
  # django
  DJANGO_HOST: django
  DJANGO_PORT: 8000
  # tomcat
  TOMCAT_HOST: tomcat
  TOMCAT_PORT: 8080

volumes:
  postgres: {}

networks:
  backend:
    driver: bridge

services: 
  postgres:
    container_name: tal-postgres
    image: postgres:11.5-alpine
    environment:
      POSTGRES_DB: wsp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    restart: on-failure:5

  django:
    container_name: tal-django
    build: ./django
    image: wsp-django:latest
    depends_on: 
      - postgres
    environment:
      <<: *system-network
      # configs
      DJANGO_SETTINGS_MODULE: core.settings
      DJANGO_SECRET_KEY: '_a_secret_key_'
      DJANGO_DEBUG: 'True'
      # dev database
      DATABASE_URL: postgres://user:1234@postgres:5432/wsp
    volumes:
      - ./django:/django
    networks:
      - backend
    ports:
      - "8000:8000"
    command: >
      sh -c "/wait-for-it.sh postgres:5432 -t 10 &&
            gunicorn --bind 0.0.0.0:8000 core.wsgi"
    restart: on-failure:5

  tomcat:
    container_name: tal-tomcat
    build: ./tomcat
    image: wsp-tomcat:latest
    volumes:
      - ./logs/tomcat:/usr/local/tomcat/logs
      - ./tomcat/conf:/usr/local/tomcat/conf
      - ./tomcat/webapps:/usr/local/tomcat/webapps
    networks:
      - backend
    ports:
      - "8080:8080"
    command: >
      sh -c "catalina.sh run"
    restart: on-failure:5

  nginx:
    container_name: tal-nginx
    image: nginx:1.17-alpine
    depends_on:
      - django
      - tomcat
    environment:
      <<: *system-network
      NGINX_HOST: localhost
      NGINX_PORT: 80
    volumes:
      - ./nginx/service.template:/etc/nginx/conf.d/service.template
      - ./django/staticfiles:/var/www/wsp/static
      - ./logs/nginx:/var/log/nginx
    networks:
      - backend
    ports:
      - "80:80"
    command: >
      sh -c "envsubst '
              $$DJANGO_HOST $$DJANGO_PORT
              $$TOMCAT_HOST $$TOMCAT_PORT
              $$NGINX_HOST  $$NGINX_PORT
              ' < /etc/nginx/conf.d/service.template > /etc/nginx/conf.d/default.conf &&
            nginx -g 'daemon off;'"
    restart: on-failure:5
  