apiVersion: v1
kind: Service
metadata:
  namespace: takealook
  name: svc-main
  labels:
    app: main
    component: revprx
spec:
  type: LoadBalancer
  selector:
    app: main
    component: revprx
    color: blue
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  namespace: takealook
  name: svc-api
  labels:
    app: main
    component: api
spec:
  type: NodePort
  selector:
    app: main
    component: api
    color: blue
  ports:
  - port: 8000

---
apiVersion: v1
kind: Service
metadata:
  namespace: takealook
  name: svc-jspvue
  labels:
    app: main
    component: jspvue
spec:
  type: NodePort
  selector:
    app: main
    component: jspvue
    color: blue
  ports:
  - port: 8080
