apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: takealook
  name: dp-revprx-blue
  labels:
    app: main
    component: revprx
    color: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: main
      component: revprx
      color: blue
  template:
    metadata:
      namespace: takealook
      labels:
        app: main
        component: revprx
        color: blue
    spec:
      volumes:
        - name: v-http
          persistentVolumeClaim:
            claimName: pvc-nfs
      containers:
        - name: cnt-revprx
          image: gcr.io/take-a-look-257807/gateway-nginx:init
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 80
          volumeMounts:
            # shared static files
            - name: v-http
              subPath: static
              mountPath: /var/www/http/static
              readOnly: yes
            # shared media files
            - name: v-http
              subPath: media
              mountPath: /var/www/http/media
              readOnly: yes
          envFrom:
            - configMapRef:
                name: cfg-revprx
                
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: takealook
  name: dp-api-blue
  labels:
    app: main
    component: api
    color: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: main
      component: api
      color: blue
  template:
    metadata:
      namespace: takealook
      labels:
        app: main
        component: api
        color: blue
    spec:
      volumes:
        - name: v-http
          persistentVolumeClaim:
            claimName: pvc-nfs
      containers:
        - name: cnt-api
          image: gcr.io/take-a-look-257807/backend-django:init
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 300m
              memory: 1Gi
          ports:
            - containerPort: 8000
          volumeMounts:
            # writable shared media directory for service
            - name: v-http
              subPath: media
              mountPath: /django/media
          envFrom:
            - configMapRef:
                name: cfg-api
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: backend.django.secret
            - name: DATABASE_URL
              valueFrom:  
                secretKeyRef:
                  name: secret
                  key: backend.django.database.url

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: takealook
  name: dp-rs-blue
  labels:
    app: main
    component: jspvue
    color: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: main
      component: jspvue
      color: blue
  template:
    metadata:
      namespace: takealook
      labels:
        app: main
        component: jspvue
        color: blue
    spec:
      containers:
        - name: cnt-jspvue
          image: gcr.io/take-a-look-257807/frontend-tomcat:init
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 8080
