apiVersion: v1
kind: Service
metadata:
  namespace: takealook
  name: svc-main
spec:
  type: LoadBalancer
  selector:
    app: main
    color: blue
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
