apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: takealook
  name: dp-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      namespace: takealook
      labels:
        app: db
    spec:
      volumes:
        - name: v-postgres
          persistentVolumeClaim:
            claimName: pvc-nfs
      containers:
        - name: cnt-postgres
          image: postgres:11.5-alpine
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: v-postgres
              subPath: postgres
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              value: takealook
            - name: POSTGRES_USER
              value: tal
            - name: POSTGRES_PASSWORD
              value: g7152fa
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
