apiVersion: v1
kind: ConfigMap
metadata:
  namespace: takealook
  name: config
data:
  project.id: "take-a-look"
  project.name: "Take a Look"
  # network configurations; related with system structure
  backend.django.host: "localhost"
  backend.django.port: "8000"
  frontend.tomcat.host: "localhost"
  frontend.tomcat.port: "8080"
