apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: takealook
  name: hpa-main
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 30
    type: Resource
  scaleTargetRef:
    kind: Deployment
    name: deployment-main-green
