apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: takealook
  name: deployment-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      namespace: takealook
      labels:
        app: db
    spec:
      containers:
        - name: container-postgres
          image: postgres:11.5-alpine
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: takealook
          - name: POSTGRES_USER
            value: tal
          - name: POSTGRES_PASSWORD
            value: g7152fa
          resources:
            limits:
              cpu: 700m
              memory: 512Mi
